[mypy]

# Force type annotations
disallow_untyped_defs = True

# Type check the interior of functions without type annotations
check_untyped_defs = True

# Disallow usage of types that come from unfollowed imports
disallow_any_unimported = True

# Don't automatically treat arguments with None default value as implicitly optional
implicit_optional = True

# Warn when returning a value with type Any from a function declared to return a non-Any type
warn_return_any = True

# Warns about casting an expression to an inferred type
warn_redundant_casts = True

# Warns about unused '# type: ignore' comments
warn_unused_ignores = True

# Handle okonomiyaki.versions as it is not yet typed
[mypy-okonomiyaki.versions]
ignore_missing_imports = True
